USE [master]
GO
/****** Object:  Database [GESTIONALE_AUTO]    Script Date: 11/09/2026 16:01:30 ******/
CREATE DATABASE [GESTIONALE_AUTO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GESTIONALE_AUTO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\GESTIONALE_AUTO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GESTIONALE_AUTO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\GESTIONALE_AUTO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GESTIONALE_AUTO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GESTIONALE_AUTO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET ARITHABORT OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET  ENABLE_BROKER 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET  MULTI_USER 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GESTIONALE_AUTO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GESTIONALE_AUTO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [GESTIONALE_AUTO] SET QUERY_STORE = ON
GO
ALTER DATABASE [GESTIONALE_AUTO] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [GESTIONALE_AUTO]
GO
/****** Object:  Table [dbo].[Assicurazioni]    Script Date: 11/09/2026 16:01:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Assicurazioni](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Id_veicolo] [int] NOT NULL,
	[Compagnia] [nvarchar](50) NULL,
	[nome] [nvarchar](50) NULL,
	[Numero_polizza] [nvarchar](50) NULL,
	[Data_ultimo_pagamento] [datetime] NULL,
	[Data_scadenza] [datetime] NULL,
	[Periodo_di_tolleranza] [int] NULL,
	[Importo] [decimal](10, 2) NULL,
	[note] [nvarchar](max) NULL,
	[ClasseDiMerito] [nvarchar](50) NULL,
 CONSTRAINT [PK_Assicurazioni] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Bolli]    Script Date: 11/09/2026 16:01:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bolli](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Id_veicolo] [int] NOT NULL,
	[inizio_validita] [datetime] NULL,
	[fine_validita] [datetime] NULL,
	[scadenza] [datetime] NULL,
	[nome] [varchar](50) NULL,
	[importo] [decimal](10, 2) NULL,
	[note] [nvarchar](max) NULL,
 CONSTRAINT [PK_Bolli] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Config]    Script Date: 11/09/2026 16:01:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Config](
	[Chiave] [nvarchar](50) NOT NULL,
	[Valore] [bit] NULL,
 CONSTRAINT [PK_Config] PRIMARY KEY CLUSTERED 
(
	[Chiave] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ImpostazioniEmail]    Script Date: 11/09/2026 16:01:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ImpostazioniEmail](
	[Destinatario] [nvarchar](20) NOT NULL,
	[TipoAvviso] [nvarchar](20) NOT NULL,
	[Giorni] [int] NOT NULL,
	[UpdatedAt] [datetime] NOT NULL,
 CONSTRAINT [PK_ImpostazioniEmail] PRIMARY KEY CLUSTERED 
(
	[Destinatario] ASC,
	[TipoAvviso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Revisioni]    Script Date: 11/09/2026 16:01:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Revisioni](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](50) NULL,
	[Id_Veicolo] [int] NOT NULL,
	[Data_revisione] [date] NULL,
	[Data_scadenza] [date] NULL,
	[Esito] [varchar](20) NULL,
	[Km] [int] NULL,
	[Importo] [decimal](10, 2) NULL,
	[Centro_revisione] [varchar](150) NULL,
	[Note] [varchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tagliando]    Script Date: 11/09/2026 16:01:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tagliando](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Id_veicolo] [int] NOT NULL,
	[nome] [nvarchar](50) NULL,
	[data_scadenza] [datetime] NULL,
	[scadenza_km] [nvarchar](50) NULL,
	[note] [nvarchar](max) NULL,
	[importo] [decimal](10, 2) NULL,
	[Data_tagliando] [datetime] NULL,
 CONSTRAINT [PK_Tagliando] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TestRealtime]    Script Date: 11/09/2026 16:01:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TestRealtime](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Messaggio] [nvarchar](255) NULL,
	[DataModifica] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Veicoli]    Script Date: 11/09/2026 16:01:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Veicoli](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Brand] [nvarchar](50) NOT NULL,
	[Modello] [nvarchar](100) NOT NULL,
	[Immatricolazione] [datetime2](7) NULL,
	[ProprietaLeasing] [nvarchar](50) NULL,
	[Contratto] [nvarchar](max) NULL,
	[TelepassSINO] [bit] NULL,
	[TelepassNumero] [nvarchar](50) NULL,
	[SecondaChiave] [nvarchar](50) NULL,
	[Assegnazione] [nvarchar](50) NULL,
	[Targa] [nvarchar](10) NULL,
	[Note] [nvarchar](max) NULL,
	[CreatedAt] [datetime2](7) NULL,
	[UpdatedAt] [datetime2](7) NULL,
	[Azienda] [nvarchar](50) NULL,
	[EmailAssegnatario] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Veicoli_Targa] UNIQUE NONCLUSTERED 
(
	[Targa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Assicurazioni]  WITH CHECK ADD  CONSTRAINT [FK_Assicurazioni_Auto] FOREIGN KEY([Id_veicolo])
REFERENCES [dbo].[Veicoli] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Assicurazioni] CHECK CONSTRAINT [FK_Assicurazioni_Auto]
GO
ALTER TABLE [dbo].[Bolli]  WITH CHECK ADD  CONSTRAINT [FK_Bolli_Auto] FOREIGN KEY([Id_veicolo])
REFERENCES [dbo].[Veicoli] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Bolli] CHECK CONSTRAINT [FK_Bolli_Auto]
GO
ALTER TABLE [dbo].[Revisioni]  WITH CHECK ADD  CONSTRAINT [FK_Revisioni_Auto] FOREIGN KEY([Id_Veicolo])
REFERENCES [dbo].[Veicoli] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Revisioni] CHECK CONSTRAINT [FK_Revisioni_Auto]
GO
ALTER TABLE [dbo].[Tagliando]  WITH CHECK ADD  CONSTRAINT [FK_Tagliandi_Auto] FOREIGN KEY([Id_veicolo])
REFERENCES [dbo].[Veicoli] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Tagliando] CHECK CONSTRAINT [FK_Tagliandi_Auto]
GO
ALTER TABLE [dbo].[ImpostazioniEmail]  WITH CHECK ADD  CONSTRAINT [CK_ImpostazioniEmail_Destinatario] CHECK  (([Destinatario]=N'owner' OR [Destinatario]=N'admin'))
GO
ALTER TABLE [dbo].[ImpostazioniEmail] CHECK CONSTRAINT [CK_ImpostazioniEmail_Destinatario]
GO
ALTER TABLE [dbo].[ImpostazioniEmail]  WITH CHECK ADD  CONSTRAINT [CK_ImpostazioniEmail_Giorni] CHECK  (([Giorni]>=(0) AND [Giorni]<=(90)))
GO
ALTER TABLE [dbo].[ImpostazioniEmail] CHECK CONSTRAINT [CK_ImpostazioniEmail_Giorni]
GO
ALTER TABLE [dbo].[ImpostazioniEmail]  WITH CHECK ADD  CONSTRAINT [CK_ImpostazioniEmail_Tipo] CHECK  (([TipoAvviso]=N'tagliando' OR [TipoAvviso]=N'revisione' OR [TipoAvviso]=N'bollo' OR [TipoAvviso]=N'assicurazione'))
GO
ALTER TABLE [dbo].[ImpostazioniEmail] CHECK CONSTRAINT [CK_ImpostazioniEmail_Tipo]
GO
USE [master]
GO
ALTER DATABASE [GESTIONALE_AUTO] SET  READ_WRITE 
GO
